version: '3.8'

services:
  api:
    build: .
    container_name: django_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=seu_projeto.settings
    depends_on:
      - db
      - queue

  db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  queue:
    image: redis:latest
    container_name: redis_queue
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: django_worker
    command: ["celery", "-A", "seu_projeto", "worker", "--loglevel=info"]
    depends_on:
      - queue
      - db

volumes:
  mongo_data:
